
[[dependencies]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.8.19"

[[dependencies]]
  name = "github.com/robfig/cron"
  revision = "df38d32658d8788cd446ba74db4bb5375c4b0cb3"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/sys"

[[dependencies]]
  branch = "master"
  name = "gopkg.in/yaml.v2"
