
[[dependencies]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.8.19"

[[dependencies]]
  branch = "master"
  name = "github.com/robfig/cron"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/sys"

[[dependencies]]
  branch = "master"
  name = "gopkg.in/yaml.v2"
